// <auto-generated />
namespace PRSServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedPurchaseRequestsController : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedPurchaseRequestsController));
        
        string IMigrationMetadata.Id
        {
            get { return "201806281505533_added PurchaseRequestsController"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
